### ISSUE TITLE
Question: Traits within py_class!()

### ISSUE THREAD

**Issue by forensicmatt** [dgrunwald/rust-cpython#113]
I am trying to create a Python class that contains the following struct which requires a struct that implements Read+Seek trait:

https://github.com/forensicmatt/r-winreg/blob/master/src/hive.rs#L24
```rust
#[derive(Serialize,Debug)]
pub struct Hive<Rs> {
    #[serde(skip_serializing)]
    source: Rs,
    baseblock: Box<BaseBlock>,
    node_stack: Vec<Box<NodeKey>>,
    current_path: String
}
```

I created a PyFio struct to implement Read and Seek which contains a pointer to the PyObject which is a file-like object:

https://github.com/forensicmatt/r-pyfio/blob/master/src/pyfio.rs#L8
```rust
pub struct PyFio {
    io_object: Box<PyObject>
}
...
impl Read for PyFio {
...
impl Seek for PyFio {
...
```

My idea was to use PyFio as the source for Hive struct. **Below is what I am trying to do but not sure how to implement the Rs for Hive within the py_class!()**.

https://github.com/forensicmatt/r-pyfio/blob/master/src/pyreg.rs
```rust
use pyfio::PyFio;
use rwinreg::hive::Hive;
use cpython::{Python, PyObject, PyResult};
use std::io::{Read,Seek};
use std::cell::RefCell;

py_class!(class RegClass | py | {
    data inner: RefCell<Hive<Rs>>;

    def __new__(_self, fileio: PyObject) -> PyResult<RegClass> {
        let py_fio = PyFio::new(
            fileio
        );

        let hive = Hive::from_source(
            py_fio
        ).unwrap();

        RegClass::create_instance(py, hive)
    }
});
```

The build error:
```
error[E0412]: cannot find type `Rs` in this scope
 --> src\pyreg.rs:8:30
  |
8 |     data inner: RefCell<Hive<Rs>>;
  |                              ^^ not found in this scope
```

Any insight or ideas for this? I am not sure if I am going about this the right way.

**Comment by dgrunwald** [comment]
Python classes can't be generic. You'll have to use a concrete type argument (`Hive<PyFio>` or whatever `Hive::from_source` is returning).
Alternatively you use type erasure: use `RefCell<Box<ErasedHive>>` where `ErasedHive` is a trait that is implemented for all `Hive<Rs>`

**Comment by forensicmatt** [comment]
Thanks for the help. I ended up just making a PyHive struct that used PyFilo as a source instead of traits.
