### ISSUE TITLE
macOS error: Could not compile `cpython`.

### ISSUE THREAD

**Issue by mkatychev** [dgrunwald/rust-cpython#138]
Hi there, I cannot compile cpython and here is the message I get pretty consistently using `cargo build` with rustc 1.24.1:
```
Compiling cpython v0.1.0
error[E0425]: cannot find function `PyEval_ThreadsInitialized` in module `ffi`
--> /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cpython-0.1.0/src/pythonrun.rs:55:26
|
55 |             assert!(ffi::PyEval_ThreadsInitialized() != 0);
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function `PyEval_ThreadsInitialized` in module `ffi`
--> /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cpython-0.1.0/src/pythonrun.rs:58:26
|
58 |             assert!(ffi::PyEval_ThreadsInitialized() == 0);
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function `PyEval_InitThreads` in module `ffi`
--> /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cpython-0.1.0/src/pythonrun.rs:65:18
|
65 |             ffi::PyEval_InitThreads();
|                  ^^^^^^^^^^^^^^^^^^ did you mean `PyEval_SaveThread`?

error[E0425]: cannot find function `PyEval_InitThreads` in module `ffi`
--> /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cpython-0.1.0/src/lib.rs:333:10
 |
333 |     ffi::PyEval_InitThreads();
 |          ^^^^^^^^^^^^^^^^^^ did you mean `PyEval_SaveThread`?

error: aborting due to 4 previous errors

error: Could not compile `cpython`.

```
Cargo.toml:
```
[package]
name = "rustpy-test"
version = "0.1.0"
authors = ["mkatychev"]

[features]
python3-sys = ["cpython/python3-sys"]

[lib]
name="rustpy"
crate-type=["cdylib"]
path = "src/lib.rs"

[dependencies.cpython]
git = "https://github.com/dgrunwald/rust-cpython.git"
default-features = false
# features = ["python27-sys"]
features = ["python3-sys"]
```

PATH: `/usr/local/bin/python3.6:/Users/$USER/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
PKG_CONFIG_PATH: `/Library/Frameworks/Python.framework/Versions/3.6/lib/pkgconfig`

I have 3.7 bound to `python3` alias through homebrew at `/usr/local/bin/python3` as a symlink, don't know if that would cause an issue.

specs:
```
 OS: 64bit Mac OS X 10.13.5 17F77
 WM: Quartz Compositor
 WM Theme: Blue
 CPU: Intel Core i5-7500 @ 3.40GHz
 GPU: Radeon Pro 570
 RAM: 9396MiB / 16384MiB
```

**Comment by dgrunwald** [comment]
What does this Python code output?

```py
import sysconfig
config = sysconfig.get_config_vars()
print(config['WITH_THREAD'])
```

`python3-sys/build.rs` will run `python3` to get some configuration settings that affect the Python ABI. It looks like it didn't detect the threading feature for your python. An interpreter without support for threads cannot be safely used from Rust.

**Comment by mkatychev** [comment]
@dgrunwald 
Using `python3.6`:
```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> config = sysconfig.get_config_vars()
>>> print(config['WITH_THREAD'])
1
```
`python3` however gave me a key error for `config['WITH_THREAD']`, does `build.rs` look for the python3 alias explicitly?

**Comment by dgrunwald** [comment]
`python3-sys` will try:
 * `$PYTHON_SYS_EXECUTABLE`
 * `python`
 * `python3`
 * If an expected version 3.X is configured, `python3-X`
Of those interpreters, it will pick the first one that works and is compatible with the configured expected version (by default, any Python 3.* interpreter will do).
So if you want to use a specific interpreter, set the PYTHON_SYS_EXECUTABLE environment variable.
You can also use the cargo features `python3-4` etc. to tell the build script to look for a specific version.

**Comment by mkatychev** [comment]
@dgrunwald 
`rm python3 && mv python3.6 python3` in /usr/local/bin did the trick for compiling, thank you!

Using the .so from doing this `cp -R target/release/librustpy.dylib ~/Documents/python/rust_test/librustpy.so` however gets me: 
`ImportError: dynamic module does not define init function (initlibrustpy)` similar to #644
setting `export PYTHON_SYS_EXECUTABLE=\`which python3\`` game me the same issue.
Both attempts failed at import using python 3.6 and 2.7

**Comment by ssokolow** [comment]
`ImportError: dynamic module does not define module export function (PyInit_librustpy)`
`ImportError: dynamic module does not define init function (initlibrustpy)`

That's a problem with your `py_module_initializer!` call inside `lib.rs`. It has to match the filename.

For example, I have something which uses `py_module_initializer!(core, initcore, PyInit_core, ...)` with the following snippet from `Cargo.toml` and it produces `core.cpython-34m.so` on my Kubuntu 14.04 LTS system.

```toml
[lib]
name = "core"
crate-type = ["cdylib"]
```

**Comment by mkatychev** [comment]
@ssokolow Yes, I should have realised sooner! Is the `lib*.dylib` prefix meant to concatenate the filename (`lib.rs` in this case) to the project name?

**Comment by ssokolow** [comment]
Unless MacOS does things differently, no. The crate name, final filename, and symbols fed to `py_module_initializer!` will only have `lib` in them if you want them to.

(Python modules don't have to begin with `lib*` and compiled modules follow the same naming conventions.)

**Comment by kigawas** [comment]
It also fails on macOS Python 3.7 and unfortunately setting `PYTHON_SYS_EXECUTABLE` to the path of Python 3.6 doesn't seem to work 😕 

Only add version configuration like:
```
[dependencies]
cpython = "0.1"
```
Should I change anything else to make it work?
