### ISSUE TITLE
Cargo.toml for module example in readme doesn't work on Windows 10 with Python 2.7

### ISSUE THREAD

**Issue by AaronM04** [dgrunwald/rust-cpython#151]
Hi, I tried compiling and importing the `rust2py` example in your README.md but I had various errors. To fix these errors, I tried modifying the Cargo.toml as follows:
```
[package]
name = "rust2py"
version = "0.1.0"
authors = ["me"]

[lib]
crate-type = ["dylib"]

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]
```
...but it gave this error:
```
λ python -c "import rust2py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define init function (initrust2py)
```

To fix this, I had to rename the DLL by adding a `name` line to the `[lib]` section in my Cargo.toml:

```
[package]
name = "rust2py"
version = "0.1.0"
authors = ["me"]

[lib]
name = "librust2py"
crate-type = ["dylib"]

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]
```

Then finally I could import this in python after copying target\debug\librust2py.dll to librust2py.pyd:
```
>>> import librust2py
>>> librust2py.sum_as_string(2,2)
'4'
```

**Comment by markbt** [comment]
I've fixed up the example, so hopefully this won't be a problem in the future.  You'll still need to rename the file, but that's unavoidable as cargo and python have different naming conventions.
