### ISSUE TITLE
Early deallocation problem for class ?

### ISSUE THREAD

**Issue by gracinet** [dgrunwald/rust-cpython#164]
Hi there, I encounter some sporadic segmentation faults or bus errors with cpython.rs bindings I wrote for Mercurial (a version control system written in python2).

My crate builds a single shared library, which contains a submodule:

```
$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mercurial import rustext
>>> rustext.__file__
'mercurial/rustext.so'
>>> dir(rustext)
['GraphError', '__doc__', '__file__', '__name__', '__package__', 'ancestor']
>>> dir(rustext.ancestor)
['AncestorsIterator', '__doc__', '__name__', '__package__']
```

I analysed the core dumps with gdb, they always look as if the `AncestorsIterator` or the `ancestor` module or their dicts get deallocated too early. Most of the times, it happens during Python shutdown, but I've seen it happen even earlier once or twice.

Does this ring a bell to anyone ?

I'm of course wondering if I got the module and class registration right. Here's what I'm doing:

Excerpt from `lib.rs`:

```rust
#[macro_use]
extern crate cpython;
mod exceptions;
mod ancestors;

py_module_initializer!(rustext, initrustext, PyInit_rustext, |py, m| {
    m.add(py, "__doc__", "Mercurial core concepts - Rust implementation")?;

    m.add(py, "ancestor", ancestors::init_module(py)?)?;
    m.add(py, "GraphError", py.get_type::<exceptions::GraphError>())?;
    Ok(())
});
```

Excerpt from `ancestors.rs`:

```rust
py_class!(class AncestorsIterator |py| {
   ...
}

pub fn init_module(py: Python) -> PyResult<PyModule> {
    let m = PyModule::new(py, "ancestor")?;
    m.add(py, "__doc__",
          "Generic DAG ancestor algorithms - Rust implementation")?;
    m.add_class::<AncestorsIterator>(py)?;
    Ok(m)
}
```

I tried a few variations without success.

To reproduce, you need mercurial (hg) to grab the code, build, and then run the whole test suite:

```
hg clone -r b9d21c31ab43 https://bitbucket.org/gracinet/mercurial-devel segfault-mercurial-devel
cd segfault-mercurial-devel
HGWITHRUSTEXT= make local  # also needs gcc, Python.h etc.
ls mercurial/rustext.so  # just a check it's been built
cd tests
python run-tests.py --local -j 12  # adjust to number of CPU threads on your system, it seems a bit of stress helps
```

Depending on your system, each test run takes 5 to 15 minutes. I don't get segfaults each time, but it's more common than not, hence 3-4 of them at most will get you an issue.

I tried to analyse by instrumenting the destructors, running with a custom-build CPython, adding debugging prints, that sort of thing, but the problem vanishes as soon as I interfere (or I haven't been lucky).

I can provide more information if needed, any hints would be appreciated, thanks !

**Comment by quark-zju** [comment]
I think you'll need to implement the `__traverse__` interface. See http://dgrunwald.github.io/rust-cpython/doc/cpython/macro.py_class.html#garbage-collector-integration.

**Comment by gracinet** [comment]
@quark-zju thanks for your reply.
I didn't think I had to implement `__traverse__` for this class, because it can't be part of any cycles and I have another version with custom-made bindings in C that doesn't need `tp_traverse`, but I realize there'll always be a doubt about it, so I gave it a try, and it didn't change anything.

I also just tried simply without a submodule, just exposing my class at the top of the extension (still with `__traverse__` in case one'd wonder), and I still got a Bus error and a Segmentation fault. It seems to be less frequent in that setup (errors appeared only in fourth full tests run), but I'd need to compare hours long runs to be positive about that. Really thought for a while that was the cultprit, though.

**Comment by yuja** [comment]
I ran the test suite for 11 times (5 by system python, 6 by --without-pymalloc build), but
I couldn't reproduce the issue. I made some changes on top of b9d21c31ab43 to fix
import error and out-of-bounds read, but that should be unrelated to the issue.

I got some SEGV by running the tests with ASAN-enabled Python, but they all appear to be
occurred while post-process of the leak sanitizer, so I'm not sure how to interpret the result.
No leak nor double free was reported.

```
Tracer caught signal 11: addr=0x0 pc=0x7faa7c0e7580 sp=0x7faa7625ad00
==5208==LeakSanitizer has encountered a fatal error.
==5208==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==5208==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
[1]
```

ASAN Python was built as follows:
```
$ ./configure --prefix=$HOME/opt/python-2.7-asan --without-pymalloc --enable-unicode=ucs4 \
CFLAGS='-O2 -fsanitize=address -fno-omit-frame-pointer -g -fwrapv -fstack-protector-strong -Wall' \
LDFLAGS=-lasan
$ ASAN_OPTIONS=detect_leaks=0 make -j4
```

and built Mercurial with it:
```
$ make local PYTHON=python-2.7-asan PYTHON_SYS_EXECUTABLE=python-2.7-asan HGWITHRUSTEXT= 
```

**Comment by gracinet** [comment]
@yuja thank you for trying that.
Oddly enough, I can't reproduce anymore on the latest version of my code, although I didn't change much (I'm also testing on a clean system to avoid side effects from local attempts to understand the issue).

Keeping the issue open for now, because I'm currently trying to narrow it down, but it will take some time, because of the length of the test runs.

**Comment by gracinet** [comment]
Time to put this issue at rest. I haven't had the slightest problem since last comment. Whatever caused it is gone.

**Comment by ssokolow** [comment]
If you can't identify the cause, how can you be sure it's not a case of invoking undefined behaviour and that it's still present, just not currently causing visible problems?

The "but the problem vanishes as soon as I interfere (or I haven't been lucky)" certainly leans in that direction.

**Comment by gracinet** [comment]
Well should have said that in the meanwhile I've run a few hundred times the very same test suite where I used to have the problem at least once every other runs. Also nobody else than me ever reproduced, including some bots that use this code for performance measurements.

But you're right, this is not like the proper way to get certainty, as in understanding the condition, then finding a way to reproduce it systematically and finally killing it.

I'll reopen if ever I see it again.
