### ISSUE TITLE
rust-cpython fails to build on Mac

### ISSUE THREAD

**Issue by traff** [dgrunwald/rust-cpython#17]
Compiling python27-sys v0.0.6
failed to run custom build command for `python27-sys v0.0.6`
Process didn't exit successfully: `target/debug/build/python27-sys-c6f0449b2a9ec4bf/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"python-2.7\"` did not exit successfully: exit code: 1\n--- stderr\nPackage python-2.7 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `python-2.7.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'python-2.7\' found\n"', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729

**Comment by novocaine** [comment]
Is the system python the only python on the box, or are there other pythons? Homebrew? python.org? What OS X version?

From a quick glance, it appears that pkg_config::find_library is not throwing even though there is no python-2.7, but then pkg_config::Config::get_variable does - invalid assumption on my part. So I think that .unwrap should be a try!.

I might not be able to get to this on my mac for a few days, but in the meantime, you will need to compile against a python that actually populates pkgconfig, like the python from homebrew for example.

There might be further problems with the system python anyway, if that's what you're using - it's usually a bit quirky and old, and I haven't tested with it

**Comment by traff** [comment]
OSX 10.10.3 Yosemite 

I've installed Python with brew, but it still doesn't work.
I've checked the installation and it seems that it misses .pc:

mbp:Projects traff$ brew ls python
/usr/local/Cellar/python/2.7.9/bin/2to3
/usr/local/Cellar/python/2.7.9/bin/2to3-2
/usr/local/Cellar/python/2.7.9/bin/2to3-2.7
/usr/local/Cellar/python/2.7.9/bin/easy_install
/usr/local/Cellar/python/2.7.9/bin/easy_install-2.7
/usr/local/Cellar/python/2.7.9/bin/idle
/usr/local/Cellar/python/2.7.9/bin/idle2
/usr/local/Cellar/python/2.7.9/bin/idle2.7
/usr/local/Cellar/python/2.7.9/bin/pip
/usr/local/Cellar/python/2.7.9/bin/pip2
/usr/local/Cellar/python/2.7.9/bin/pip2.7
/usr/local/Cellar/python/2.7.9/bin/pydoc
/usr/local/Cellar/python/2.7.9/bin/pydoc2
/usr/local/Cellar/python/2.7.9/bin/pydoc2.7
/usr/local/Cellar/python/2.7.9/bin/python
/usr/local/Cellar/python/2.7.9/bin/python-config
/usr/local/Cellar/python/2.7.9/bin/python2
/usr/local/Cellar/python/2.7.9/bin/python2-config
/usr/local/Cellar/python/2.7.9/bin/python2.7
/usr/local/Cellar/python/2.7.9/bin/python2.7-config
/usr/local/Cellar/python/2.7.9/bin/pythonw
/usr/local/Cellar/python/2.7.9/bin/pythonw2
/usr/local/Cellar/python/2.7.9/bin/pythonw2.7
/usr/local/Cellar/python/2.7.9/bin/smtpd.py
/usr/local/Cellar/python/2.7.9/bin/smtpd2.7.py
/usr/local/Cellar/python/2.7.9/bin/smtpd2.py
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/ (3717 files)
/usr/local/Cellar/python/2.7.9/IDLE.app/Contents/ (8 files)
/usr/local/Cellar/python/2.7.9/libexec/pip/ (512 files)
/usr/local/Cellar/python/2.7.9/libexec/setuptools/ (251 files)
/usr/local/Cellar/python/2.7.9/Python Launcher.app/Contents/ (17 files)
/usr/local/Cellar/python/2.7.9/share/man/ (3 files)
/usr/local/Cellar/python/2.7.9/share/python/ (315 files)

**Comment by traff** [comment]
I've installed now Python 2.7.10 from Mac installer and it contains python-2.7.pc, setting the  PKG_CONFIG_PATH=/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig solved the problem.

**Comment by traff** [comment]
Thanks!

**Comment by novocaine** [comment]
okay cool.

for reference, homebrew only recently fixed their pkgconfig: https://github.com/Homebrew/homebrew/commit/d5f029cfeac46acbed2b81b786c2bc0fb61f96cd

so updating the formula and reinstalling may also do the trick if you want to use that homebrew python.

**Comment by traff** [comment]
Indeed, thanks!

**Comment by traff** [comment]
Now I have another issue:

failed to run custom build command for `python3-sys v0.1.0 (https://github.com/dgrunwald/rust-cpython.git#43552a07)`
Process didn't exit successfully: `/Users/traff/Projects/snakemeter/sampler/target/debug/build/python3-sys-57907895b44fdff8/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=python3.4m
cargo:rustc-link-search=native=/Library/Frameworks/Python.framework/Versions/3.4/lib

--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run python interpreter `\"/Library/Frameworks/Python.framework/Versions/3.4/bin/python\" \"-c\" \"import sysconfig; config = sysconfig.get_config_vars();print(config.get(\\\'Py_USING_UNICODE\\\', 0));print(config.get(\\\'Py_UNICODE_WIDE\\\', 0));print(config.get(\\\'WITH_THREAD\\\', 0));print(config.get(\\\'Py_DEBUG\\\', 0));print(config.get(\\\'Py_REF_DEBUG\\\', 0));print(config.get(\\\'Py_TRACE_REFS\\\', 0));print(config.get(\\\'COUNT_ALLOCS\\\', 0));print(config.get(\\\'Py_UNICODE_SIZE\\\', None));\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:731


Note, that I have Python executable in /Library/Frameworks/Python.framework/Versions/3.4/bin but it called python3 not python

**Comment by novocaine** [comment]
Uh oh .. I can't replicate that.

with python3.4 from python.org, and PKG_CONFIG_PATH=/Library/Frameworks/Python.framework/Versions/3.4/lib/pkgconfig, python3-sys compiles without issue. 

What is supposed to happen is configure_from_pkgconfig sniffs the exec_prefix of your python distro and then tries to locate the python interpreter underneath that, trying the most specifically versioned interpreter first, using fs::metadata to check the existance of a possible interpreter path. The order should be python3 (at which point it should succeed for you, then exit), then python.

The path to the interpreter returned by configure_from_pkgconfig is then used in get_config_vars, which is where your build.rs is blowing up. Are you able to do me a favour and debug around the end of configure_from_pkgconfig function to find out how exactly is it settling on an interpreter path that doesn't exist?

**Comment by traff** [comment]
Sure, I'' try to debug it.

**Comment by novocaine** [comment]
Replicated this when python3 is detected on os x using PATH, not with pkgconfig (I had figured this was on the pkgconfig path based on previous discussion).

**Comment by dgrunwald** [comment]
Is this still an issue, or was this fixed in #28?
