### ISSUE TITLE
Python class TypeError

### ISSUE THREAD

**Issue by josephok** [dgrunwald/rust-cpython#178]
I defined a Python class and invoked, it triggered TypeError, below is my Python code and Rust code :
```py
# test_hello.py
import hello


class TestMe:
    age = 20


t = TestMe()
print(hello.print_py_object(t))
```

```rust
// lib.rs
#[macro_use]
extern crate cpython;

use cpython::{PyObject, PyResult, Python};

py_class!(class TestMe |py| {
    data age: i32;
});

fn print_py_object(py: Python, obj: PyObject) -> PyResult<String> {
    let v = obj.cast_as::<TestMe>(py)?;
    let out = format!("{}", v.age(py));
    Ok(out)
}

py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(
        py,
        "print_py_object",
        py_fn!(py, print_py_object(val: PyObject)),
    )?;

    Ok(())
});
```

I don't know what's wrong, all I want to do is pass Python class to a Rust function. I want to get fields in that Python class, please help me. Thanks.

**Comment by ssokolow** [comment]
The problem is that declaring two different classes with the same name doesn't make them the same class. Rust is just calling you on something that would still be a mistake in Python:

```py
# foo.py
class TestMe:
    pass
```

```
>>> import foo
>>> class TestMe:
...     pass
... 
>>> a = TestMe()
>>> isinstance(a, foo.TestMe)
False
```

**Comment by josephok** [comment]
@ssokolow Thanks for reply. I don't mean they are the same name, I want to convert Python class to Rust(Maybe Struct) so I can map the fields in class, `age` in that example. I use `cast_as` as the docs says it.

**Comment by ssokolow** [comment]
If you want to manipulate objects with types declared in Python, you have to act on the understanding that Rust can't see their definition, so they have to be all treated as the same type from Rust's perspective and you have to use the `PyObject` methods.

For example, here's a modified version of your code that I just finished testing which shows how to accomplish the literal effect of your test.

```
// lib.rs
#[macro_use]
extern crate cpython;

use cpython::{PyObject, PyResult, Python};
use cpython::ObjectProtocol;

fn print_py_object(py: Python, obj: PyObject) -> PyResult<String> {
    let obj_pystr = obj.str(py)?;
    let out = format!("{}", obj_pystr.to_string(py)?);
    Ok(out)
}

py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(
        py,
        "print_py_object",
        py_fn!(py, print_py_object(val: PyObject)),
    )?;

    Ok(())
});
```

Surprisingly, I haven't yet gotten to the point where I needed `py_class!` yet (all my algorithms have been fine with handling strings or lists of strings), so give me a moment to get familiar with it and I'll try to give you a sample of doing something more like what you want.

**Comment by josephok** [comment]
@ssokolow All I know is `py_class!`, maybe there are some other ways to do this. (Map Python class to Rust struct)

**Comment by ssokolow** [comment]
There are two ways, depending on whether or not you declare your class in Python or Rust. Give me another couple of minutes and I'll give you working examples for both.

**Comment by ssokolow** [comment]
OK. Here's the finished stuff.

If you want to access stuff on classes declared in Python code, Rust only understands them as instances of `PyObject` (ie. a tree of fancy `dict`/`HashMap`-style containers), so here's what you have to do:

```py
# test_hello.py
import hello

class TestMe:
    age = 20

t = TestMe()
print(hello.print_py_object(t))
```

```rust
// lib.rs
#[macro_use]
extern crate cpython;

use cpython::{PyObject, PyResult, Python};
use cpython::ObjectProtocol;

fn print_py_object(py: Python, obj: PyObject) -> PyResult<String> {
    let v: i32 = obj.getattr(py, "age")?.extract(py)?;
    let out = format!("{}", v);
    Ok(out)
}

py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(
        py,
        "print_py_object",
        py_fn!(py, print_py_object(val: PyObject)),
    )?;

    Ok(())
});
```

...and if you want to use native Rust types, you have to declare the classes in Rust like this:

```py
# test_hello.py
import hello

t = hello.TestMe()
print(hello.print_py_object(t))

```

```rust
// lib.rs
#[macro_use]
extern crate cpython;

use cpython::{PyObject, PyResult, Python};
use cpython::ObjectProtocol;

py_class!(class TestMe |py| {
    data age: i32;
    def __new__(_cls, age: i32 = 20) -> PyResult<TestMe> {
        TestMe::create_instance(py, age)
    }
});

fn print_py_object(py: Python, obj: PyObject) -> PyResult<String> {
    let v = obj.cast_as::<TestMe>(py)?;
    let out = format!("{}", v.age(py));
    Ok(out)
}

py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(
        py,
        "print_py_object",
        py_fn!(py, print_py_object(val: PyObject)),
    )?;
    m.add_class::<TestMe>(py)?;

    Ok(())
});
```

**Comment by josephok** [comment]
@ssokolow That works very well, thanks.

**Comment by ssokolow** [comment]
No problem. :)

**Comment by ssokolow** [comment]
Oh, if you choose the "declared on the Rust side" option, you'll want to read the [Data declarations section of the `py_class!` docs](https://dgrunwald.github.io/rust-cpython/doc/cpython/macro.py_class.html#data-declarations)

**Comment by josephok** [comment]
I have one more question, if I declare the class on the Python side and `age` is a function(such can called by `t.age()`). How can I invoke this Python function in Rust?

**Comment by josephok** [comment]
Found it, use `PyObject.call_method()`
https://dgrunwald.github.io/rust-cpython/doc/cpython/trait.ObjectProtocol.html#method.call_method

**Comment by josephok** [comment]
Solved.
