### ISSUE TITLE
Compile failed in Debian 10

### ISSUE THREAD

**Issue by tataDan** [dgrunwald/rust-cpython#184]
I have python 3.7.3 installed on Debian 10.  I have a copy of the example program shown in the README.md on my computer.  When I "cargo run" the project, the dependencies are downloaded but cpython does not compile.  Apparently libpython3.7m cannot be found.  The output shows this error message at the beginning of the output:
`error: linking with `cc` failed: exit code: 1`
and these messages at the end:
` = note: /usr/bin/ld: cannot find -lpython3.7m
          collect2: error: ld returned 1 exit status     

error: aborting due to previous error

error: Could not compile `cpython`.
`
How can this issue be resolved?

**Comment by ssokolow** [comment]
Do you have the `python3-dev` package installed or just the base `python3` package intended to save disk space in situations where all your Python-requiring applications are delivered precompiled?

**Comment by tataDan** [comment]
I did not have the python3.7-dev package installed.  After I installed it, the program compiled and  ran without issues.
Thank you for your quick and helpful response.

**Comment by ssokolow** [comment]
No problem. :)

If you consider this done, would you mind closing this issue? I'm just a fellow user who likes to help out, so I can't do it for you.
