### ISSUE TITLE
Expose Rust functions when interpereting Python

### ISSUE THREAD

**Issue by manhnt9** [dgrunwald/rust-cpython#188]
Hi, how can I register Rust functions to the interpreter so I don't have to load external .so module to call Rust functions in Python? Does this project support that?

Pseudo-code:
```rust
extern crate cpython;

use cpython::{Python, PyDict, PyResult};

fn func() -> PyResult<String> {
    return "Hello from Rust";
}

fn main() {
    let gil = Python::acquire_gil();
    hello(gil.python()).unwrap();
    // register func() to Python
    let res: String = py.eval("func()")?.extract(py)?;
}
```

**Comment by manhnt9** [comment]
Found it: https://dgrunwald.github.io/rust-cpython/doc/cpython/macro.py_fn.html

**Comment by ssokolow** [comment]
For anyone else who wanders in here, I'd like to point out that `py_fn!` is used the same way whether you're building an importable module or an embedded runtime. The only difference in a line like this...

```rust
m.add(py, "sum_as_string", py_fn!(py, sum_as_string_py(a: i64, b:i64)))?;
```

...is whether the `m` is coming from `py_module_initializer!` or `let m = PyDict::new(py);`. (With the latter then being given to `py.eval` or `py.run` as the `globals` or `locals` parameter.)

**Comment by manhnt9** [comment]
Thanks. Anyways I think we should add this example to the readme so people would know another popular use case. I myself spent like 1 hour trying to find clues about this.
