### ISSUE TITLE
Marshalling Rust Structs into Python Classes

### ISSUE THREAD

**Issue by vegapit** [dgrunwald/rust-cpython#196]
Hi,

Quick questions: Is it possible to export **Rust Structs** as **Python Classes** and use their methods from within Python? If so, is there an example code that covers this functionality?

**Comment by gracinet** [comment]
Yes, it is possible, but not direct: you have to rewrap your inner Rust Struct as a proper Python class defined in Rust, using the [py_class macro](https://docs.rs/cpython/0.3.0/cpython/macro.py_class.html)

You need also to activate the `extension-module` compilation feature (see README).

The above linked doc contains an example with very simple data (an `i32`). Things get more complicated with data that is not `Copy`, like presumably your Rust struct, see the [Data declarations](https://docs.rs/cpython/0.3.0/cpython/macro.py_class.html?search=#data-declarations) section.

**Comment by vegapit** [comment]
Thank you for the clear answer. I was somehow hoping it would be easy to work with `Vec` as Struct members, so I guess I need to rethink my plans.
