### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by gracinet** [dgrunwald/rust-cpython#214]
We have many important changes in the current `master`: on the top of my head: Rust properties, code modernization, Python 3.8 symbols, so a release seems to be in order.

I think it should be labeled 0.5.0, and I'm planning to do it at the end of this week. This issue to create some awareness about that. That will probably take the form of a PR a day or two before.

**Comment by indygreg** [comment]
Do you need any help crafting a PR to perform the release?

**Comment by dtolnay** [comment]
Look like 0.5.0 was released to crates.io on April 8, so this can be closed. https://crates.io/crates/cpython/0.5.0
