### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_libfastpython)

### ISSUE THREAD

**Issue by dark0ghost** [dgrunwald/rust-cpython#224]
I did everything as indicated in the documentation but I get:
`import libfastpython
ImportError: dynamic module does not define module export function (PyInit_libfastpython)`

os: debian 10
cargo  - https://gist.github.com/dark0ghost/a619a366adad549da75ea608a78b1e98
lib.rs - https://gist.github.com/dark0ghost/0c946a807072189ea2ea81ab3ec0b8f0

**Comment by ssokolow** [comment]
Because the `py_module_initializer!(rust2py` in the code you pasted is generating a module export function named `PyInit_rust2py` instead.

**Comment by dark0ghost** [comment]
thk
