### ISSUE TITLE
Error using python27

### ISSUE THREAD

**Issue by thymbahutymba** [dgrunwald/rust-cpython#226]
I get the following error using python 2.7
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { ptype: <type 'exceptions.ImportError'>, pvalue: Some('__import__ not found'), ptraceback: Some(<traceback object at 0x7f7f729516e0>) }', src/python.rs:12:5
```
```
const TASKGEN_STR: &'static str = include_str!("../taskgen.py");

fn module_from_str(py: Python<'_>, name: &str, source: &str) -> PyResult<PyModule> {
    // Create a new empty module named
    let module = PyModule::new(py, name).unwrap();

    // Run the contents of `taskgen_str` in the context of `module` to populate the module
    py.run(source, Some(&module.dict(py)), None).unwrap();

    Ok(module)
}
```

```
[dependencies.cpython]
version = "0.5"
default-features = false
features = ["python27-sys"]
```

The same script edited with 2to3 in order to run with python3 works fine. I don't know what else I can provide. How can I solve this?

**Comment by ssokolow** [comment]
`__import__ not found` is the error, but I don't have time to experiment with guessing at the contents of `taskgen.py` until I replicate the observed behaviour.

(At the moment, I'm working to revive a site that didn't get adequate testing before a PHP 7.2 upgrade rolled out and broke it.)

**Comment by thymbahutymba** [comment]
Yes sorry I forgot to send you the link to [taskgen.py](https://github.com/jlelli/taskgen/blob/master/taskgen.py) in the previous comment.

**Comment by ssokolow** [comment]
Sorry for going silent. I'm currently trying to get 500-ing website back online, so I'll probably have to wait until Sunday or Monday afternoon to get back to you on that.

(The site didn't keep up with the updates to the framework it's based on and didn't have automated tests, so I'm having to write some tests and migrate across a major revision change to the framework at the same time.)

**Comment by ssokolow** [comment]
OK, I've managed to reproduce the problem and I tried to find an explanation for the difference in behaviour between Python 2.7 and 3.x.

However, the most likely candidate I could find is [this comment from 2012 on StackOverflow](https://stackoverflow.com/questions/13307110/can-you-recover-from-reassigning-builtins-in-python/13307417#comment18155424_13307417) which points out that Python 3.x removed Python 2.x's doomed efforts to implement a restricted mode.

Specifically, this passage from [the manual](https://docs.python.org/2/library/restricted.html):

> The Python run-time determines whether a particular code block is executing in restricted execution mode based on the identity of the __builtins__ object in its global variables: if this is (the dictionary of) the standard __builtin__ module, the code is deemed to be unrestricted, else it is deemed to be restricted.

I wasn't able to figure out how to get this working by plumbing things together on the Rust side (and, given the rust-cpython and [python embedding](https://docs.python.org/2/extending/embedding.html#very-high-level-embedding) docs, it sounds like it should Just Work™), which makes me suspect it to be a bona fide bug in rust-cpython.

However, here's a way to implement it which works for me under Python 2.7 as a workaround:

```rust
use cpython::{Python, PyDict, PyModule, PyResult};

const TASKGEN_STR: &str = include_str!("../taskgen.py");

fn module_from_str(py: Python<'_>, name: &str, source: &str) -> PyResult<PyModule> {
    let module = PyModule::new(py, name)?;
    let locals = PyDict::new(py);
    locals.set_item(py, "module", &module)?;
    locals.set_item(py, "source", source)?;

    py.run("exec source in module.__dict__", None, Some(&locals))?;

    Ok(module)
}

fn main() {
    let gil = Python::acquire_gil();

    let module = module_from_str(gil.python(), "taskgen", &TASKGEN_STR).unwrap();
    println!("Hello, world!");
}
```

(I tested it by adding `test = "foo"` to `taskgen.py` and `    println!("Hello, world! {}", module.get(gil.python(), "test").unwrap());
` worked as expected.)

**Comment by ssokolow** [comment]
\*facepalm* I just realized what the problem was and how to fix it **properly**.

Add this line before you call `py.run`.

```rust
module.add(py, "__builtins__", py.eval("__builtins__", None, None)?)?;
```

**Comment by thymbahutymba** [comment]
Thanks for the help!
