### ISSUE TITLE
Some property macros do not use $crate:: access

### ISSUE THREAD

**Issue by HeroicKatora** [dgrunwald/rust-cpython#234]
This issue affects code that declares classes with properties through `py_class!/@property`. In [`slots.rs`](https://github.com/dgrunwald/rust-cpython/blob/7fb4dd2e59ccf0fbf6bbe874b602e52b8aa4a8c1/src/py_class/slots.rs) some of the macros use bare names instead of `$crate::_` when using others. This makes it necessary to manually import the referred to names on use. In particular, there are bare uses of `py_class_prop_getter`, `py_class_prop_setter`, `py_class_call_slot_impl_with_ref` and potentially others.

**Comment by markbt** [comment]
Thanks for the report!  I've created #235 to fix them.  I think I got them all, but let me know if you find any more.
