### ISSUE TITLE
Execute code by importing the module

### ISSUE THREAD

**Issue by eLteammate** [dgrunwald/rust-cpython#238]
Let's say my module requires some precalculations. Usually, I would do this like so: 
```
# module.py

def job():
    do_stuff()
    do_more_stuff()
    ...

job()
```
Now `job` will be executed when I do `import module` for the first time. In c-api it is possible by using multi-phase initialization. But how do I do this using Rust? I wasn't able to find an answer in docs nor sources. Is this feature is not supported, or am I missing something?
I guess I can edit `__loader__` object, override `__code.__func__` attribute with my loader function, which calls my `job` function, but it seems too overcomplicated. Alternatively, I can use static variables, and every time I need a `job` result, check if it was already computed and compute it if it was not. Is there another, more "pythonic" workaround?

**Comment by ssokolow** [comment]
`py_module_initializer!`'s second argument is a closure/lambda/anonymous function (note the vertical bars).  You're not just limited to calling `m.add` in there.

Here's a tweak to the example from the README:

```rust
py_module_initializer!(rust2py, |py, m| {
    m.add(py, "__doc__", "This module is implemented in Rust.")?;
    m.add(py, "sum_as_string", py_fn!(py, sum_as_string_py(a: i64, b:i64)))?;
    println!("Hello World!");
    Ok(())
});
```

```
>>> import rust2py
Hello World!
>>> 
```

**Comment by eLteammate** [comment]
This makes sense. Thank you for your help!
