### ISSUE TITLE
clippy::manual_strip lint triggers with Rust v1.48.0

### ISSUE THREAD

**Issue by tdyas** [dgrunwald/rust-cpython#245]
The `clippy::manual_strip` triggers when using the `cpython` crate with Rust v1.48.0. https://rust-lang.github.io/rust-clippy/master/index.html#manual_strip

Probably from https://github.com/dgrunwald/rust-cpython/blob/68ace18a38996fbdeb2ae61ea4d413ac283f4c0a/src/lib.rs#L406-L407

**Comment by markbt** [comment]
Unfortunately `strip_prefix` was only added in 1.45, so we can't use it yet.   We can add an `allow(clippy::manual_strip)` to the code, though.

**Comment by markbt** [comment]
I suppressed this lint for now.  Once we update MSRV past 1.45 we can fix the usage.
