### ISSUE TITLE
the test_thread_exit test fails on s390x

### ISSUE THREAD

**Issue by decathorpe** [dgrunwald/rust-cpython#249]
When building cpython and running the test suite for eventual builds for Fedora, the `test_thread_exit` test fails consistently on s390x hardware, but passes on all other architectures (x86_64, i686, aarch64, armv7hl, ppc64le). The only output from the failing test is `FATAL: exception not rethrown`. I am unsure why s390x behaves differently here. The only difference I can think of is that it's the only big-endian architecture Fedora officially supports.

```
     Running `/builddir/build/BUILD/cpython-0.5.2/target/release/deps/test_thread_exit-99ba3f1827ab08df`
running 1 test
FATAL: exception not rethrown
```

At the end of the `cargo test` output, there's also this:

```
error: test failed, to rerun pass '--test test_thread_exit'
Caused by:
  process didn't exit successfully: `/builddir/build/BUILD/cpython-0.5.2/target/release/deps/test_thread_exit-99ba3f1827ab08df` (signal: 6, SIGABRT: process abort signal)
```

Maybe the SIGABRT causes the test to fail in an unexpected way.

**Comment by decathorpe** [comment]
Oh, after submitting a PR for a different change, I see that the CI also sometimes fails with this error, even on other architectures. So it might not have anything to do with the architecture, but maybe it's just a race condition or something?

**Comment by markbt** [comment]
It looks like the test is just flaky.  I'm not actually sure it works the way we intend it to.

Changing the timing by adding a longer sleep in the spawned thread makes it reliably pass.  That suggests that if the thread never gets to execute then the test will pass.

The sleep in the main thread happens with the GIL held.  Wrapping it with `py.allow_threads` means the thread actually gets to start and that makes the test reliably fail for me.

With the reliable test, it looks like this regressed in rustc 1.48.  The test passes on rustc 1.47.

Will investigate more.

**Comment by markbt** [comment]
This shouldn't be a problem now that #252 is merged (the test will be disabled).

**Comment by decathorpe** [comment]
Thanks for investigating! That "solves" my problem, so I'm closing this ticket.
