### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by justinhalf** [dgrunwald/rust-cpython#25]
I'm trying to get a hello world example running but have been unsuccessful so far.  My code is here for reference https://github.com/justinhalf/py-rust-hello-world

I'm able to `cargo build` but when I try to import in python, I get:

```bash
PYTHONPATH=target/debug/ python -c "import libhello_world"
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

After I compiled the rust code, I didn't get a .so file.  I'm working around that for now by doing ```(cd target/debug/ && ln -s libhello_world.dylib libhello_world.so)```.  I also get a compile failure unless I ```export PKG_CONFIG_PATH=/Users/justin/anaconda/envs/rust-python/lib/pkgconfig/```.  

I tried some googling and it seems like it could be related to the rust code being linked against the wrong python libraries.  I am running anaconda and using the rust-python environment that I pointed the PKG_CONFIG_PATH variable at.  I'm using rust-nightly and am on OSX.

I'm a bit stuck at this point.  Any suggestions would be greatly appreciated.

**Comment by novocaine** [comment]
I have seen this error when the Python interpreter being executed doesn't
match the one linked against.

**Comment by justinhalf** [comment]
Do you know how I can debug further to find the interpreter being linked against?

This the output from otool: 

```
otool -L target/debug/libhello_world.dylib
target/debug/libhello_world.dylib:
	/Users/justin/code/py-rust-hello-world/target/debug/libhello_world.dylib (compatibility version 0.0.0, current version 0.0.0)
	libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

libpython2.7.dylib doesn't have any path, so I'm not sure if it's the right one.  I am running python 2.7.
Also, I thought updating PKG_CONFIG_PATH was how I was telling the rust linker which python to link against.  Do you know if that's true, or if there's another way I can tell it which one to use?

**Comment by novocaine** [comment]
I suspect you are getting (at runtime) the system's libpython2.7 but you
are running some other python.

This has clues on how that .dylib might be resolved at runtime:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html

What is the contents of the .pc file in /Users/justin/
anaconda/envs/rust-python/lib/pkgconfig ?

What is the error you receive when you don't set that pkg variable? The
build script is supposed to fall back to the python in your PATH if it
cannot locate a pkg file - this allows it to work seamlessly with
virtualenv.

**Comment by justinhalf** [comment]
These are the contents of the .pc file
```
cat /Users/justin/anaconda/envs/rust-python/lib/pkgconfig/python2.pc
prefix=/Users/justin/anaconda/envs/rust-python
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Python library
Requires:
Version: 2.7
Libs.private: -ldl  -framework CoreFoundation
Libs: -L${libdir} -lpython2.7
Cflags: -I${includedir}/python2.7
```

This is the error I get when building without PKG_CONFIG_PATH set

```
cargo build -v
       Fresh interpolate_idents v0.0.3
       Fresh regex-syntax v0.2.1
       Fresh winapi-build v0.1.1
       Fresh rustc-serialize v0.3.15
       Fresh winapi v0.2.1
       Fresh abort_on_panic v1.0.0
       Fresh pkg-config v0.3.5
       Fresh libc v0.1.8
       Fresh memchr v0.1.3
       Fresh aho-corasick v0.3.0
       Fresh advapi32-sys v0.1.2
   Compiling num v0.1.25
     Running `rustc /Users/justin/.cargo/registry/src/github.com-0a35038f75765ae4/num-0.1.25/src/lib.rs --crate-name num --crate-type lib -g --cfg feature=\"rustc-serialize\" --cfg feature=\"bigint\" --cfg feature=\"default\" --cfg feature=\"rand\" --cfg feature=\"complex\" --cfg feature=\"rational\" -C metadata=7ad397ad0b46ae38 -C extra-filename=-7ad397ad0b46ae38 --out-dir /Users/justin/code/py-rust-hello-world/target/debug/deps --emit=dep-info,link -L dependency=/Users/justin/code/py-rust-hello-world/target/debug/deps -L dependency=/Users/justin/code/py-rust-hello-world/target/debug/deps --extern rand=/Users/justin/code/py-rust-hello-world/target/debug/deps/librand-f6ba3f8ee27431ba.rlib --extern rustc_serialize=/Users/justin/code/py-rust-hello-world/target/debug/deps/librustc_serialize-c1e8163a38ed3d54.rlib --cap-lints allow`
   Compiling python27-sys v0.1.0
     Running `/Users/justin/code/py-rust-hello-world/target/debug/build/python27-sys-81c89ffea2c9b535/build-script-build`
       Fresh regex v0.1.41
       Fresh rand v0.3.9
Build failed, waiting for other jobs to finish...
failed to run custom build command for `python27-sys v0.1.0`
Process didn't exit successfully: `/Users/justin/code/py-rust-hello-world/target/debug/build/python27-sys-81c89ffea2c9b535/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "unknown linkmodel shared"', ../src/libcore/result.rs:732
```


I'm reading through that link you sent about dyld now.  Thanks for your help so far.

**Comment by novocaine** [comment]
That "unknown linkmodel shared" error is from
https://github.com/dgrunwald/rust-cpython/blob/master/python27-sys/build.rs#L212

Just checking the contents of MacOS.c from the py2.7 sources, I think the
string "dynamic" in there is not right and should be "shared". Can you try
editing the build script locally and see if that gets any further for you?

**Comment by justinhalf** [comment]
That fixes the build error so I no longer need to set PKG_CONFIG_PATH.  

I'm still getting the PyThreadState_Get error when I try to run python though.  I've been playing around with the dyld paths, but so far no luck.

**Comment by novocaine** [comment]
Does it by any chance work if you try to load it with the system python?

If I have some spare time this weekend I can try to replicate - never used
anaconda before, is it enough to just download the stock os x distro from
their site?

**Comment by justinhalf** [comment]
Good call, that works.  Thank you so much!

```
PYTHONPATH=target/debug/ /usr/bin/python -c "import libhello_world; libhello_world.hello_world()"
Hello, world!
```

And for anaconda, all I did was download it from them and use ```conda create --name rust-python python``` then ```source activate rust-python``` to switch to that environment.

**Comment by novocaine** [comment]
Okay cool. Still need to understand why the build has created a
non-absolute dynamic link, and whether its related to the anaconda
interpreter, I'll follow that up when I get a chance.
