### ISSUE TITLE
PyObjectArenaAllocator error

### ISSUE THREAD

**Issue by ryancinsight** [dgrunwald/rust-cpython#257]
Hello,

On pythons website:
Pyobjectarenaallocator is denoted as:
void *ctx | user context passed as first argument
void* alloc(void *ctx, size_t size) | allocate an arena of size bytes
void free(void *ctx, size_t size, void *ptr) | free an arena

yet you have written as:
pub struct PyObjectArenaAllocator {
    pub ctx: *mut c_void,
    pub alloc: Option<extern "C" fn(ctx: *mut c_void, size: size_t) -> *mut c_void>,
    pub free: Option<extern "C" fn(ctx: *mut c_void, ptr: *mut c_void, size: size_t) -> ()>,

switching the size and pointer in free...

Wouldn't this cause memory allocation issues?

**Comment by markbt** [comment]
As discussed in #258 this is actually a bug in the Python docs.  The `rust-cpython` code matches the CPython header.
