### ISSUE TITLE
Accessing PyBytes data without holding the GIL?

### ISSUE THREAD

**Issue by SimonSapin** [dgrunwald/rust-cpython#271]
`cpython::PyBytes` has this method: `fn data(&self, _py: Python<'_>) -> &[u8]`. It takes a GIL marker, but is that really necessary? Would it be sound to have a safe `&PyBytes -> &[u8]` method? This could be useful to write a multi-threaded algorithm that uses some bytes from Python as input, without copying.

First, the lifetime of the returned slice is tied to that of the `PyBytes` object (as it should) but not to the `'_` lifetime of the GIL marker. So it seems already possible to call `data`, release the GIL, and keep accessing the returned slice; all in safe code. (This may involve jumping through a few hoops like starting a scoped thread.)

Second, looking at the implementation: `PyBytes::data` calls CPython’s `PyBytes_AsString` and `PyBytes_Size`. They each do a type check (which can raise an exception) then simply return a C struct field. Raising an exception probably requires the GIL, but when starting from `PyBytes` instead of `PyObject` the type is presumed to be correct. In fact `PyBytes::data` does not check for NULL or -1 return values from `PyBytes_AsString` and `PyBytes_Size` for possible exceptions. So it seems that `PyBytes::data` only reads immutable data, which should be thread-safe.

But perhaps rust-cpython should not rely on implementation details of current versions of CPython. However I could not easily find documentation one way or another about which APIs are safe to use without the GIL.

For now I made a module that looks like this, that uses but try to minimize `unsafe` code. Does this looks wrong?

```rust
pub(super) struct PyBytesWithData {
    #[allow(unused)]
    keep_alive: PyBytes,

    /// Borrows the buffer inside `self.keep_alive`,
    /// but the borrow-checker cannot express self-referential structs.
    data: *const [u8],
}

fn require_send<T: Send>() {}

#[allow(unused)]
fn static_assert_pybytes_is_send() {
    require_send::<PyBytes>;
}

// Safety: PyBytes is Send. Raw pointers are not by default,
// but here sending one to another thread is fine since we ensure it stays
// valid.
unsafe impl Send for PyBytesWithData {}

impl PyBytesWithData {
    pub fn new(py: Python, bytes: PyBytes) -> Self {
        Self {
            data: bytes.data(py),
            keep_alive: bytes,
        }
    }

    pub fn data(&self) -> &[u8] {
        // Safety: the raw pointer is valid as long as the PyBytes is still
        // alive, and the returned slice borrows `self`.
        unsafe { &*self.data }
    }

    pub fn unwrap(self) -> PyBytes {
        self.keep_alive
    }
}
```

**Comment by dgrunwald** [comment]
`PyBytes_AsString` might internally temporarily modify reference counts; calling it without the GIL would be relying on implementation details.
Using the returned pointer without the GIL should be fine. It's not like cpython could start using a copying garbage collector, as existing C extensions already assume the data pointer can continue to be used after other calls into the interpreter (some of which may temporarily release the GIL if an interpreter loop is involved).

So I think it's fine to use scoped threads or your `PyBytesWithData` type.

**Comment by SimonSapin** [comment]
Ok, so:

* Getting a `&'a [u8]` out of `&'a PyBytes` while holding the GIL and then keep accessing the slice without the GIL is fine, as already reflected by its lifetime not being connected to the one in the `Python<'_>` marker.
* Getting that slice without the GIL at all is not safe without cooperation from CPython such as adding an hypothetical C API that would document that guarantee

Sounds reasonable, thanks!
