### ISSUE TITLE
Implement trait on type created with `py_class!` macro

### ISSUE THREAD

**Issue by rapodaca** [dgrunwald/rust-cpython#278]
I'd like to implement a Rust trait on a type created with the `py_class!` macro. The following compiles:

```rust
py_class! {class Foo |py| {
    data number: usize;
}}

trait Bar {
    fn get_number(&self) -> usize;
}

impl Bar for Foo {
    fn get_number(&self) -> usize {
        todo!("return self.number")
    }
}
```

However, when I try to access the field `number` from `Foo`, I need to pass a `Python` value. The following won't work because I don't have the python lock:

```rust
fn get_number(&self) -> usize {
    // "py" is not available here
    self.number(py).clone()
} 
```

How can I implement a trait on a CPython-derived type in which I access the internal data without the `Python` lock?

**Comment by dgrunwald** [comment]
Use `Python::acquire_gil()` to acquire the GIL.

Python code might be accessing your object from multiple threads, so the GIL is necessary to avoid data races.

**Comment by rapodaca** [comment]
Thanks - it worked. Here's the full method I used:

```rust
impl Bar for Foo {
    fn get_number(&self) -> usize {
        let gil = Python::acquire_gil();

        self.number(gil.python()).clone()
    }
}
```
