### ISSUE TITLE
Top-level imports/variables not global by default on rust-cpython?

### ISSUE THREAD

**Issue by elonen** [dgrunwald/rust-cpython#290]
Scoping seems to work somehow differently inside rust-cpython and a command-line python interpreter.
One requires the use of `global` keyword, while the other doesn't:

### Standalone cpython
Running this simple program through CLI (e.g. `python3 test.py`)...

```python
test_var = 123

def test_func(txt):
    print("Calling from", txt)
    print("test_var =", test_var)

test_func("Python @ CLI")
```

...prints, as expected:
```
Calling from  Python3 @ CLI
test_var = 123
```

### Rust-cpython
However, running the same inside **rust-cpython**...
```rust
fn py_func_call_test() -> PyResult<()> {
    let code = r##"
test_var = 123

def test_func(txt):
    print("Calling from", txt)
    print("test_var =", test_var)

test_func("Python @ rust-cpython")
"##;

    let gil = Python::acquire_gil();
    let py = gil.python();
    let (globals, locals) = (PyDict::new(py), PyDict::new(py));
    py.run(code, Some(&globals), Some(&locals))?;    
    Ok(())
}
```
...results in a *variable not defined* error:
```
Calling from Python @ rust-cpython
Error: Error: PyErr { ptype: <class 'NameError'>, pvalue: Some("name 'test_var' is not defined"), ptraceback: Some(<traceback object at 0x7ff402bdac80>) }
```

If you add an explicit `global`, it works:

```rust
    let code = r##"
global test_var
test_var = 123

def test_func(txt):
    print("Calling from", txt)
    print("test_var =", test_var)

test_func("Python @ rust-cpython")
"##;
```
Result:
```
Calling from Python @ rust-cpython
test_var = 123
```

**Am I perhaps missing some boilerplate or is this a bug?**

### Some context
My ultimate goal is to let users write app extensions in Python by calling their functions from Rust side, like this:
```rust
    // Call the function from Rust
    let test_func = locals.get_item(py, "test_func").unwrap();
    test_func.call(py, ("Rust",), None)?;
```

After adding the `global`, this actually works as expected...
```
Calling from Rust
test_var = 123
```
...but I'm worried users would be surprised and confused about why their Python code requires different scoping directives inside rust-cpython and standalone cpython.

**Comment by elonen** [comment]
Hmm. This also happens with imports. The following...
```python
import traceback

def test_func():
    traceback.print_exc()

test_func()
```
...fails with `name 'traceback' is not defined` when executed with `py.run(code, Some(&globals), Some(&locals))?;`

Import statement needs to go inside the def to make this work, i.e. this works:
```python
def test_func():
    import traceback
    traceback.print_exc()

test_func()
```

**Comment by dgrunwald** [comment]
If you use
```
    let (globals, locals) = (PyDict::new(py), PyDict::new(py));
    py.run(code, Some(&globals), Some(&locals))?;   
```
then any variable set at top-level scope will end up in `locals` (unless you use the `global` keyword).

If you want to evaluate the code as usual for module-level code, you need to pass `None` for the `locals` dict.

**Comment by elonen** [comment]
## Solution

It seems that if you don't pass a `locals` dict to `run()`, assignments go into `globals` dict.
That is, if the code is to assign stuff into `globals` on top level, use this...
```rust
    py.run(code, Some(&globals), None)?;   // Works. Imports and assignments go into globals
```
...instead of this:
```rust
    py.run(code, Some(&globals), Some(&locals))?;    // Doesn't work. Gives "undefined" errors from function call
```

The documentation of `Python.run()` (and `eval()`) currently says:

> Executes one or more Python statements in the given context.
> If globals is None, it defaults to Python module `__main__`. If locals is None, it defaults to the value of globals.

Not sure if my understanding of Python's "in given context" or the phrasing here is too vague.
Anyway, closing this and marking as solved.
