### ISSUE TITLE
Put `py: Python` argument at beginning or end of argument list?

### ISSUE THREAD

**Issue by dgrunwald** [dgrunwald/rust-cpython#33]
Now that #15 is adding a `py: Python` argument to almost every function, we should pick a consistent position for that argument.

Beginning: `fn(Python, ...)`
End: `fn(..., Python)`

Calls seem more readable to me in the beginning position:
`some_method(py, nested_call(py, long, argument, list))`
vs.
`some_method(nested_call(long, argument, list, py), py)`

If we want the non-`Copy` `Python` token, and use the beginning position, nested calls will fail to compile with Rust's current reborrowing semantics. This might or might not be fixed in a future Rust version.

However, there are [good reasons](https://github.com/dgrunwald/rust-cpython/issues/15#issuecomment-150936977) for `Python` to remain `Copy`, so I think the beginning position is the correct choice.

**Comment by ehiggs** [comment]
Beginning.
