### ISSUE TITLE
Please release a new version to crates.io

### ISSUE THREAD

**Issue by mneumann** [dgrunwald/rust-cpython#36]
The last released version 0.0.4 does no longer compiler correctly. Something like 0.0.5 or 0.1.0 would be nice, so rust-cpython can be made a dependency of other crates.io packages :)

**Comment by dgrunwald** [comment]
rust-cpython depends on nightly rust and is regularly affected by breaking changes. (interpolate_idents tends to break several times per month)

I don't think there's a point in publishing such unstable crates on crates.io, when cargo works just fine with git dependencies.

**Comment by mneumann** [comment]
cargo works fine as long as you don't want to publish a crate on crates.io. The crates you publish on crates.io MUST NOT depend on crates that aren't available on crates.io itself (rust-cpython in this case). 

but it's probably better to wait until things settle down.
