### ISSUE TITLE
Not able to define extension inside a module

### ISSUE THREAD

**Issue by Luthaf** [dgrunwald/rust-cpython#38]
First of all, this is a really good crate, thank you very much for your work! While trying it I ran into the following bug:

--- 

Defining a Rust extension for Python works fine as long as everything is in the top level module, but the following code 

```rust
#[macro_use]
extern crate cpython;

pub mod python {
    use cpython::{Python, PyResult, PyObject};

    py_module_initializer!(example, initpylum, PyInit_pylum, |py, m| {
        try!(m.add(py, "run", py_fn!(run())));
        Ok(())
    });

    fn run(py: Python) -> PyResult<PyObject> {
        println!("Rust says: Hello Python!");
        Ok(py.None())
    }
}
```

Fails to compile with 

```
<cpython macros>:10:1: 11:40 error: failed to resolve. Use of undeclared type or module `std::mem` [E0433]
[...]
<cpython macros>:10:1: 11:40 error: unresolved name `std::mem::transmute` [E0425]
[...]
error: aborting due to 2 previous errors
```

Adding an `use std;` in the `python` module fix this error.

**Comment by dgrunwald** [comment]
The new version of the `py_fn!` and `py_class!` macros should have fixed this problem.

**Comment by Luthaf** [comment]
Thank you! By the way, do you have any idea on which time scale this crate is going to be relatively stable? More like 1 month or 1 year?

**Comment by dgrunwald** [comment]
I think I'll upload a version compatible with stable Rust to crates.io relatively soon (next 2 weeks?). Before 53353d374bbfdb506b64123ee4c0eb717e5b0db6 that wasn't really useful, as `interpolate_idents` broke several times per month.

As for when the breaking changes are going to stop.. no idea.
