### ISSUE TITLE
python 3 build support

### ISSUE THREAD

**Issue by novocaine** [dgrunwald/rust-cpython#4]
Just FYI I've started working on this over at https://github.com/novocaine/rust-cpython.

I think we can parametrise the python27-sys build.rs so it can be identical across python3-sys and python27-sys, with the parameters being picked up by enabled features in the pythonX-sys/Cargo.toml. The python 3 Cargo.toml needs to have python version features to indicate which python 3 the user is trying to target via pkg-config.

I think there should be something in the doco about how the build works to stop people from having to read the build.rs, but not sure whether to put it in the README.md or in the generated docs.

**Comment by dgrunwald** [comment]
I've just pushed initial support for python 3.x in a106cabc4a8ad7bf37aec1fb8e7cff929ac9f5d4.
