### ISSUE TITLE
Reconsider ExtractPyObject

### ISSUE THREAD

**Issue by dgrunwald** [dgrunwald/rust-cpython#40]
I'm not happy with the current state of `ExtractPyObject`. In many cases, it involves unnecessary operations on the `PyObject` refcount due to the two-step operation.

I think it might more sense to separate extraction of values and references into two traits, and decide which one to use based on the syntactic form of the parameter type (handling the case distinction within the `py_argparse!()` macro instead of within the trait system).

**Comment by markbt** [comment]
I think the state of this isn't too bad now, so I'll close the issue (feel free to reopen if you think there's more work to be done).
