### ISSUE TITLE
Next release stabilization

### ISSUE THREAD

**Issue by ihrwein** [dgrunwald/rust-cpython#42]
First of all, thanks for this great library!

I started to use it for creating [Python parser](https://github.com/ihrwein/python-parser) bindings for syslog-ng. It seems like I used a work in progress version from your lib, as there were several types and macros removed I relied on (`TypeBuilder`, `py_method`).

I fixed some minor bugs (documentation, `::std::mem::transmute`) and when I wanted to send a PR I realized that there was a major refactor in `cpython` in the weekend.

Could you tell me when you want to release a new version from your library? Is the `py_class` macro  stable to use? Can I wrap a Rust object into a Python class with it (by using `|py, obj|`)?

Thank you very much for your awesome work!

**Comment by dgrunwald** [comment]
> Could you tell me when you want to release a new version from your library?  Is the py_class macro stable to use?

No idea. I like how `py_class!` has worked out so far, but some cross-cutting concerns (e.g. documentation strings) may still require a change in design. I'm also living in fear of the macro recursion limit...

> Can I wrap a Rust object into a Python class with it (by using |py, obj|)?

A `py_class` can have Rust objects as data members:
```
py_class!(class Test |py| {
    data data_name: Vec<String>;

    def some_function(&self) -> PyResult<usize> {
       self.data_name(py).size()
    }
});
```
The type `Test` then is pretty much equivalent to the old `PyRustObject<Vec<String>>`.

**Comment by ihrwein** [comment]
Thanks for the quick answer!

By wrapping a Rust object, I meant wrapping a particular instance of `Vec<String>` into `Test`. I used the `create_instance()` method for this.

**Comment by ihrwein** [comment]
I close this issue as it's just a question :)
