### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by maciejkula** [dgrunwald/rust-cpython#47]
Just thought I'd let you know that the published docs for some reason do not document all the method you have implemented (http://dgrunwald.github.io/rust-cpython/doc/cpython/struct.PyDict.html, for example). I worry that you may be selling your crate short there!

**Comment by dgrunwald** [comment]
Must have been some kind of rustdoc bug in the nightly I used. I regenerated the docs using stable Rust and it looks better now.

**Comment by maciejkula** [comment]
Thanks!
