### ISSUE TITLE
How to convert Vec<u8> to bytes instead of list

### ISSUE THREAD

**Issue by lukaspustina** [dgrunwald/rust-cpython#52]
Hi,

I'd like to convert a `Vec<u8>` to a Python object. In the current implementation, if I use `.to_py_object()`, I receive a Python list. I'd rather prefer `bytes` and IIRC in the "past" this is what rust-cpython used to  return. 

The only way I found so far is to explicitly create a `PyBytes` object which in my case leads to duplicate code -- see below.

Here is an example:

```
        let py_dict = PyDict::new(py);
        //let py_bytes: PyBytes = PyBytes::new(py, &self.data); // Will give you bytes
        let py_bytes = self.data.to_py_object(py); // Will give you list
        let _ = py_dict.set_item(py, "data", py_bytes);
        py_dict
```

A full running example can be found in this GitHub repository: https://github.com/lukaspustina/rust-cpython-exp-bytes.

Cheers,
Lukas

PS Thanks for the hard work to create this library.

**Comment by dgrunwald** [comment]
Yes, you'll have to call `PyBytes::new()`.

`Vec<T>::to_py_object()` has to work the same way for all types `T` (at least on stable Rust; but it would be highly surprising if we started to specialize some types on nightly).
It was the same way in the "past"; there never was a special-cased `Vec<u8>` implementation.

**Comment by lukaspustina** [comment]
@dgrunwald: Thanks for your response and help.
