### ISSUE TITLE
How can i use this function in the rust-cpython?

### ISSUE THREAD

**Issue by lbc001** [dgrunwald/rust-cpython#55]
The example code in Python is :
`import requests`
`print(requests.get("http://www.google.com").text)`
So i tried to write in Rust:
`let requests=py.import("requests").unwrap();`
`let requests_get=requests.get(py,"get").call(py,("http://www.google.com",),None).unwrap().get(py,"text");`
Unfortunately,i failed to get the page source..
`let requests_get=requests.get(py,"get").call(py,("http://www.google.com",),None).unwrap()`
return the `<Response [200]>`,so i can not get the `text` of the response.
I have searched in the doc but find nothing...so how can i fix this problem?

**Comment by dgrunwald** [comment]
For accessing untyped python objects, use the [ObjectProtocol](https://dgrunwald.github.io/rust-cpython/doc/cpython/trait.ObjectProtocol.html) trait:

`let requests_get=requests.get(py,"get").call(py,("http://www.google.com",),None).unwrap().getattr(py,"text");`

**Comment by lbc001** [comment]
Thanks!XD,i have solved this problem
