### ISSUE TITLE
Cannot build against python 3 without specifying a minor version

### ISSUE THREAD

**Issue by dgrunwald** [dgrunwald/rust-cpython#6]
python3-sys/build.rs expects that a specific minor version is specified.

However, the use of the PEP 384 limited ABI allows us to build against an arbitrary python3 version -- there shouldn't be a need for the user of rust-cpython to manually specify which python 3 version is installed.

**Comment by novocaine** [comment]
working on a fix now.

we should preserve the possibility of specifying an explicit minor version, for those that want to target a particular python on their machine, but it should not be mandatory.
