### ISSUE TITLE
Converting PyInt/PyLong to c_long

### ISSUE THREAD

**Issue by mackeyja92** [dgrunwald/rust-cpython#60]
How do I successfully convert a `PyInt` or `PyLong` to a `c_long`? I see that `PyInt` implements `value(py)` but `PyLong` does not. All of my code uses `PyInt` but it seems when compiling it thinks I want `PyLong` instead and so I cannot call `value(py)` on my `PyInt`.

```rust
/* 
error: no method named `value` found for type `cpython::PyLong` in the current scope
  --> rust/src/stats/mod.rs:62:10
   |
62 |     date.value(py)
   |          ^^^^^
*/ 
pub fn parse_date(py: Python, date: PyInt) -> c_long {
    date.value(py)
}


/*
error: no method named `extract` found for type `cpython::PyLong` in the current scope
  --> rust/src/stats/mod.rs:62:10
   |
62 |     date.extract(py).unwrap()
   |          ^^^^^^^
   |
   = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: candidate #1 is defined in the trait `cpython::FromPyObject`
  --> rust/src/stats/mod.rs:62:10
   |
62 |     date.extract(py).unwrap()
   |          ^^^^^^^
*/
pub fn parse_date(py: Python, date: PyInt) -> c_long {
    date.extract(py).unwrap()
}
```

**Comment by dgrunwald** [comment]
The real `PyInt` only exists in Python 2.x; in Python 3.x it's just a typedef to `PyLong`.

To convert a python object to a number, you can simply use `PyObject::extract`:

```
pub fn parse_date(py: Python, date: PyInt) -> c_long {
    date.as_object().extract::<c_long>(py).unwrap()
}
```

`extract` can be called on arbitrary python objects without converting to `PyInt` first (you'll get a `TypeError` if the object isn't an `int` or `long`).
You can also directly extract any Rust integer type (not just `c_long`), and you'll get an `OverflowError` if the value doesn't fit.

**Comment by mackeyja92** [comment]
@dgrunwald Thanks this makes sense. The part I was clearly missing and couldn't figure out was the `as_object()`
