### ISSUE TITLE
PyList::iter() not working correctly for map (and possibly others)

### ISSUE THREAD

**Issue by mackeyja92** [dgrunwald/rust-cpython#62]
When calling `list.iter(py).map(|value| {...})` it doesn't seem to actually yield the item for map. By that I mean it would never even map at all but rather just skip the loop section entirely as if the list was empty. Switching to `for value in list.iter(py) {...}` worked correctly.

**Comment by dgrunwald** [comment]
What's `list`? A `PyObject` or a `PyList`?
How do you consume the return value of the `map` call?

I would be helpful if you could provide a complete example program demonstrating the problem.

**Comment by mackeyja92** [comment]
Sorry for the delay in getting back to this. The project i was creating when I had this issue got put on the back burner and I have been swamped since then. I should be back on this project soon and can pull a few examples but until then I will close this issue.
