### ISSUE TITLE
Using PyType in pattern matching

### ISSUE THREAD

**Issue by expobrain** [dgrunwald/rust-cpython#67]
Is there a better way to execute specific code based on the of the `PyObject`? At the moment the only solution I fond is this one:

```rust
fn from_python_to_yaml(py: Python, obj: &PyObject) {
    let py_type = obj.get_type(py);
    let type_name = py_type.name(py);

    match type_name.borrow() {
        "list"      => { ... },
        "int"       => { ... },
        "str"       => { ... },
        "unicode"   => { ... },
        "dict"      => { ... },
        "float"     => { ... },
        "bool"      => { ... },
        "NoneType"  => { ... },
        _           => { println!("Unimplemented {:?}", type_name); }
    }
}
```

but is not optimal from the point of view of the performance and readability.

**Comment by dgrunwald** [comment]
Matching on the type name might produce false positives (if user-defined types have the same name), and does not detect derived types.

An efficient way to test the type of an object is to use `cast_as`:
```
if let Ok(_) = obj.cast_as::<PyList>() {
} else if let Ok(_) = obj.cast_as::<PyInt>() {
} else if let Ok(_) = obj.cast_as::<PyBytes>() {
} else if let Ok(_) = obj.cast_as::<PyUnicode>() {
}
```

For most built-in types, each `cast_as` call gets compiled into a simple check of a bitflag (e.g. `if (obj->tp->flags & Py_TPFLAGS_INT_SUBCLASS) != 0`).

I don't see a way to perform a nicely readable match on types.
