### ISSUE TITLE
Add python 3.6 support.

### ISSUE THREAD

**Issue by AraHaan** [dgrunwald/rust-cpython#68]
Python 3.6 should hopefully be released officially as the final version soon it is currently in rc1 state. This means this should allow use of this in 3.6 for those who use rust to help speed up their code. This is something really cool that even I am considering it for my iterators I had to implement in my bot to look through messages (using coroutines) and add them to a number of messages to delete. With a filter and if it was coded in rust on that part it should help it a bit.

like an example:

```py
    opt = ctx.message.content[len(self.bot.bot_prefix + "prune "):].strip()
    num = 1
    if opt:
        try:
            num = int(opt)
        except Exception as e:
            str(e)
            return
```

(note ctx is passed to a function that provides ``context`` on what the message was)
Also import hooks, what if someone was to somehow write one that uses ``importlib`` to generate an import hook like so in python:

```py
from importlib.machinery import FileFinder
import zlib
import json
import base64
import sys


class ExtensionImporter(object):
    """Base Importer Class."""
    def __init__(self, extension_list):
        self.extensions = extension_list
        self.path = None

    def find_loader(self, name, path):
        """Filds some loaders for importing the module."""
        str(name)  # use name even though we are not using it for anything.
        self.path = path
        return self

    def load_module(self, fullname):
        """Loads a module into sys.modules."""
        if fullname in sys.modules:
            return sys.modules[fullname]
        return None


class JsonImporter(ExtensionImporter):
    """JSON File Importer Class."""
    def __init__(self):
        super(JsonImporter, self).__init__(['.json'])

    def load_module(self, fullname):
        """Loads modules found with the extension"""
        premodule = super(JsonImporter, self).load_module(fullname)
        if premodule is None:
            try:
                with open(self.path) as f:
                    module = json.load(f)
                    sys.modules[fullname] = module
                    return module
            except FileNotFoundError:
                raise ImportError('Could not import the json file {0}'.format(fullname))


class PycxImporter(ExtensionImporter):
    """PYCX File Importer Class."""
    def __init__(self):
        super(PycxImporter, self).__init__(['.pycx'])

    def load_module(self, fullname):
        """
        Loads modules found with the pycx excention.

        Info: pycx files are compressed python source code files.

        Order of processing (to import):
            zlib decompression
            base64 decode.
        """
        premodule = super(PycxImporter, self).load_module(fullname)
        if premodule is None:
            try:
                with open(self.path, 'rb') as f:
                    filedata = f[len(b'PYCX'):].strip()
                    try:
                        decczfiledata = zlib.decompress(filedata)
                        decoded_data = base64.b64decode(decczfiledata)
                    except zlib.error as ex:
                        raise ImportError('Could not import {0} because of exception:\n{1}.'.format(fullname, str(ex)))
                    # assume utf8 encoding. utf8 is standard python script encoding anyways.
                    module = decoded_data.decode("utf-8")
                    sys.modules[fullname] = module
                    return module
            except FileNotFoundError:
                raise ImportError('Could not import {0}.'.format(fullname))


extension_importers = [JsonImporter(), PycxImporter()]
hook_list = []
for importer in extension_importers:
    hook_list.append((importer.find_loader, importer.extensions))

sys.path_hooks.insert(0, FileFinder.path_hook(*hook_list))
sys.path_importer_cache.clear()
```

Import hooks like these in python would be absolutely awesome to be able to code in rust instead of needing to cythonize them as cython makes code awful to read and makes the code confusing when it is cythonized.

Although then again it would be nice if rust had classes similar to python as C, C++, even Visual Basic has classes.

**Comment by dgrunwald** [comment]
Did you try Python 3.6? Unless there are breaking changes in the ABI, new python versions should just work (TM).
I just updated `python3-sys` to the 3.6 RC headers; but none of the changes looks like it was required for the `cpython` crate.

(Of course, I won't mention Python 3.6 support in the README until I've had a chance to test with the final 3.6 release)

**Comment by AraHaan** [comment]
hmm ok, I could try, also what about building subclasses within the rust crate?

**Comment by dgrunwald** [comment]
Oh right, subclasses are still missing (see #11). I had support for those earlier, but dropped initially when moving to the `py_class!` macro, and then never added it back.

**Comment by AraHaan** [comment]
ah I see.

**Comment by dgrunwald** [comment]
I just tested with the python 3.6.0 release, the python 3.6 support seems to work fine.

**Comment by AraHaan** [comment]
ok, Now I just hope you can add back in subclasses sometime when you get it to work with everything else as well. Or at least make something like an ``py_subclass`` function or something that would handle subclasses.
