### ISSUE TITLE
How do I add a class to py_module_initializer?

### ISSUE THREAD

**Issue by pashinin** [dgrunwald/rust-cpython#72]
We have a function export example:

```
py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(py, "__doc__", "Module documentation string")?;
    m.add(py, "run", py_fn!(py, run()))?;
    Ok(())
});
```

I try to create and export a class. How can I do this? I tried `py_class!` but had error:

```
try!(m.add(py, "Cls", py_class!(py, Cls)));


error: no rules expected the token `py`
```

**Comment by dgrunwald** [comment]
Documentation: https://dgrunwald.github.io/rust-cpython/doc/cpython/macro.py_class.html
Example: https://github.com/dgrunwald/rust-cpython/blob/master/extensions/tests/custom_class.rs

**Comment by pashinin** [comment]
thanks
