### ISSUE TITLE
Lifetimes in py_class!

### ISSUE THREAD

**Issue by pashinin** [dgrunwald/rust-cpython#76]
Sorry if I don't know either Rust or rust-cpython but how can I use `py_class!`with lifetime params inside it?
I want a variable `s` to live as long as class `MyType`.
```
py_class!(class MyType |py| {
    data s: Into<Cow<'a, str>>;
}
```

I wanted to write the whole class manually like
```
pub struct MyType<'a> {...}
```

But then I saw that even a macros was generated by Python script and I ran away crying...

**Comment by dgrunwald** [comment]
Nothing stops Python code from storing Python objects in a global variable, so all data contained in Python objects must be `'static`.
