### ISSUE TITLE
Docs improvement: Construct PyErr

### ISSUE THREAD

**Issue by Eh2406** [dgrunwald/rust-cpython#82]
Hi,

I am experimenting with the new buffer support with numpy. I am so stoked! This is going to be amazing!

I did get come across a confucian, how do I make a `TypeError` so I can [return from my fn](https://github.com/Eh2406/numpy-rust/blob/d54f71ddb6adc2211213ed0f421e6abba35af1db/src/lib.rs#L31)?

Also Is there anything I can do to help with the buffer support?

**Comment by dgrunwald** [comment]
Construct PyErr: `return Err(PyErr::new::<exc::TypeError, _>(py, "Not a contiguous buffer of f64"));`

You could test whether the buffer support works with numpy. Anything with `dimensions() != 1` is completely untested at the moment (numpy scalars and multi-dimensional arrays).

**Comment by Eh2406** [comment]
Can we add that to the "Error Handling" section or in the "PyErr" module or the "PyErr::new" docstring?
Can we make "PyErr::new" the first method in the module docs, I did not notes it when I was looking before I made the issue?

So this is the module I made.
```rust
py_module_initializer!(hello, inithello, PyInit_hello, |py, m| {
    m.add(py, "__doc__", "Module documentation string")?;
    m.add(py, "func", py_fn!(py, func(x: Vec<f64>)))?;
    m.add(py, "funcbuff", py_fn!(py, funcbuff(x: &PyObject)))?;
    Ok(())
});

fn func(_: Python,  x: Vec<f64>) -> PyResult<f64> {
    Ok(x.into_iter().inspect(|i| println!("{:}", i)).sum())
}

fn funcbuff(py: Python,  x: &PyObject) -> PyResult<f64> {
    let x = PyBuffer::get(py, x)?;
    let x = x.as_slice::<f64>(py).expect("not a buffer of f64"); // fix to return err
    Ok(x.into_iter().map(|i| i.get()).inspect(|i| println!("{:}", i)).sum())
}
```
This is the python2 I used to test it.
```python
x = np.arange(12.).astype('float64').reshape((-1, 2), order='c')

# print hello.func(x) # TypeError: only length-1 arrays can be converted to Python scalars
print hello.func(x[:, 1])
# print hello.func(np.float64(3)) # TypeError

print hello.funcbuff(x)
print hello.funcbuff(x[:, 1])# panicked at 'not a buffer of f64'
```
What is a good next move? Better way to write the rust? More things to test with the numpy?

**Comment by Eh2406** [comment]
[Thanks for the added docs.](https://github.com/dgrunwald/rust-cpython/commit/32e0d3560395fef9a16d01d7b61d6fdfa589c538#diff-62a73ebf355cee98e3a01bb067337e19R158)
