### ISSUE TITLE
Inadequate CI

### ISSUE THREAD

**Issue by novocaine** [dgrunwald/rust-cpython#9]
Travis is pretty inadequate for a project of this type where what's really required is a selection of build slaves for the supported platforms and python versions.

It seems like currently travis builds on linux x64 only, with python 2.7.

Raising this issue in case anyone knows of a free hosted CI platform that supports other platform types (32 bit, OS X, Windows), has a cunning free solution to the problem, or is willing to donate an instance to the problem. 

OS:
- [x] Linux
- [x] OS X
- [x] Windows

Platform:
- [X] x64
- [ ] x86

**Comment by dgrunwald** [comment]
We should be able to get travis to build python 3 as well; but I don't have an idea for the other platforms.

**Comment by novocaine** [comment]
okay, it has better support than I thought - there's os x support, although apparently they aren't accepting requests to start new instances because of load.

http://docs.travis-ci.com/user/multi-os/
http://docs.travis-ci.com/user/osx-ci-environment/
open item for 32-bit: https://github.com/travis-ci/travis-ci/issues/986
open item for windows: https://github.com/travis-ci/travis-ci/issues/2104

**Comment by dgrunwald** [comment]
http://www.appveyor.com/ offers free Windows CI, so a combination of travis and appveyor might do the job.

**Comment by dgrunwald** [comment]
We now have Windows CI: https://ci.appveyor.com/project/dgrunwald/rust-cpython

Currently it's only building and not running any tests, due to the linking issues on windows.

**Comment by dgrunwald** [comment]
Travis CI now runs with python 2.7, 3.3 and 3.4.

**Comment by pradyunsg** [comment]
Is this still an issue? If so, what all is unresolved?

**Comment by novocaine** [comment]
I think you have resolved it :)

**Comment by dgrunwald** [comment]
This issue is still open because we don't have the OSX CI enabled yet.

I [tried to enable it](https://travis-ci.org/dgrunwald/rust-cpython/builds/104168175), but travis doesn't support python on OSX out of the box: travis-ci/travis-ci#2312.

**Comment by pradyunsg** [comment]
In which case, could someone add a checklist to OP... Ticking Linux but not Windows and OSX?

Back to OSX, why not use https://github.com/MacPython/terryfy?

**Comment by ssokolow** [comment]
The version of OSX used by Travis comes with Apple's patched version of Python 2.7... they're just not set up to test alternative versions on OSX.

Here's how one of my projects tests against OSX's bundled Python:
https://github.com/ssokolow/get_user_headers/blob/master/.travis.yml

**Comment by naufraghi** [comment]
I managed to have a working OSX CI, the tradeoff is that I'm generating¹ the matrix, because I have not found a compact way to have both mac and linux working.

Here the builds: https://travis-ci.org/naufraghi/rust-cpython.

@dgrunwald, if you are interested I can cleanup my code and propose a PR with the minimal `.travis.yml` updates.

[1] The matrix is generated using [cog](http://nedbatchelder.com/code/cog/), so the burden is minimal.

**Comment by markbt** [comment]
Given how old x86 is now, I'm not sure there's much point to support it in CI.  I think the CI we have now is adequate, so I'm going to close this.
