### ISSUE TITLE
How to Best Thread Work

### ISSUE THREAD

**Issue by liveresume** [dgrunwald/rust-cpython#92]
Which approach will provide the most performance / make most sense when embedding Python in Rust?

1. Create multiple Rust threads where each thread calls a Python function.

2. Use a single Rust thread that calls a Python function which then distributes work to multiple Python owned threads.

Just getting started here and it's not obvious (unless its 1 :) which approach to choose, hopefully someone can point me in the right direction.

**Comment by ssokolow** [comment]
Python uses a Global Interpreter Lock (GIL) for thread safety, so option 2 won't get you any benefits over option 1 for CPU-bound work and option 1 will only help you if each Rust thread fires up its own copy of the Python runtime so each thread gets its own GIL.

**Comment by fafhrd91** [comment]
as I remember it is not possible to run multiple python interpreters in same process

**Comment by ssokolow** [comment]
Ahh, so, basically, back to "Don't embed Python if you're using threads for 'concurrent working' rather than 'concurrent waiting'".

(Which is what I'd normally recommend anyway. The original question already sounds sort of like "How do I sprinkle magic Rust fairy dust on my Python so I can keep coding in Python but without its biggest weakness?")

**Comment by liveresume** [comment]
So if we cannot run multiple python interpreters in the same process, in lieu of using multiple rust processes, the only solution is 2?

**Comment by liveresume** [comment]
Actually I found someone saying it is possible:

https://bytes.com/topic/python/answers/660081-multiple-python-interpreters-within-same-process

Post by Graham Dumpleton

**Comment by ssokolow** [comment]
You fundamentally misunderstand. Multiple Python threads within a single interpreter don't run in parallel.

The Python runtime has a single big lock that a thread must acquire before working on Python variables, so only one thread can be doing work at any given time.

**Comment by liveresume** [comment]
@ssokolow So even if using the wider GIL API only 1 thread can use same Python instance at a time?

**Comment by liveresume** [comment]
How about starting multiple Python instances, with a GIL per Rust thread, in the case the various Python instances don't need to share info?

**Comment by ssokolow** [comment]
That's correct. If you can run multiple Python interpreters, each will have its own isolated set of variables bound to that particular interpreter's GIL.

...I still think your "multiple apparently-CPU-bound Python threads" approach is highly questionable though. What high-level problem are you trying to solve anyway?

**Comment by liveresume** [comment]
@ssokolow There is undoubtedly a lot more scientific/math libs available for Python than Rust. I would rather use Python libs then recreate my own in Rust (I do hope in a few years that is a different story).

My goal is to do as much as possible in Rust like threading and IO, and handoff the NN and other numerical work to Python.

**Comment by ssokolow** [comment]
First, a lot of that stuff (eg. the BLAS library) will be Python wrappers around C code that can also be called directly from Rust.

Second, prototype first, then profile, *then* optimize. Don't tie yourself in knots until you have a concrete thing that needs to be faster than it is.

**Comment by liveresume** [comment]
@ssokolow Very true.  I was expecting that answer - should have added that I already have a lot written in Python which comes into consideration for me.

Beyond the fact there are better ideal approaches, you think this will work?

**Comment by fafhrd91** [comment]
usually scientific libraries release GIL during computation, so it is probably ok just use one python interpreter

**Comment by ssokolow** [comment]
It may or may not.

Given that you'll probably be depending on C extensions, it's possible that they'll be using the simpler, older GIL API from before multiple interpreters were supported in a single process... which would mean that your scientific code's lock/unlock request would lock/unlock all threads' GILs for lack of more specific information... which would bring you right back to "only one thread can run at once".

**Comment by liveresume** [comment]
@fafhrd91 It's that my work is easily 'parallelized' and therefore multiple instances are a must.  

Thankfully they are not concurrent so they don't need to share the GIL or instance.

@ssokolow Hmm, will have to see what happens as I'm not at all sure. But if it happens I bet you saved me debug time :+1:

**Comment by fafhrd91** [comment]
what I mean is if library releases GIL properly then it is file to use it from multiple python threads and it will utilize all available cpu.

**Comment by liveresume** [comment]
Would using this libs' `Python.call` or `Python.eval` passing data as args, require use of the GIL?  I ask because the GIL is used for IO right?

@fafhrd91 So if I do some number crunching with Numpy I need to thread using Python not Rust?

**Comment by liveresume** [comment]
Given the GIL's limitations with CPU-bound work I'm thinking the way to go here is multiprocessing.  Pipes are the goto, but how about shared memory? Can this lib help with that?

I'm thinking I could use [sharedctypes](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.sharedctypes) on python's side, and feed it with a function created in Rust and wrapped in `rust-cpython` to call in python.

**Comment by liveresume** [comment]
Given your intimate knowledge of rust-cpython can you comment on which approach should be faster:

1. Start multiple python processes (individual programs, single-threaded code) and communicate using pipes from Rust.

2. Start multiple Rust processes (individual programs, single-threaded code), each one uses rust-cpython to call Python, and communicate with the Rust processes using pipes from another Rust 'master' program.

I assume it depends on how rust-cpython communicates with Python, is there serialization involved or is it done with regular ctypes?  Also, when rust-cpython calls Python, does Python execute on another thread or the same thread as Rust?

**Comment by ssokolow** [comment]
My knowledge isn't really that initimate... I just have fairly broad-spectrum knowledge from developing in Python for over a decade and wanting have a decent grasp of the DOs and DON'Ts of using it.

In your situation, I'd honestly suggest testing the performance yourself. It's' entirely possible that some quirk of how you implement either solution could skew the results.

As for when rust-cpython calls Python, calls to methods on the `Python` object are synchronous, so it'd make no sense for `rust-cpython` to be spinning up another thread behind the scenes.

**Comment by dgrunwald** [comment]
There is no serialization or extra threads involved. Most functions in `rust-cpython` directly correspond to functions in the Python C API.

**Comment by liveresume** [comment]
So when rust-cpython calls a python function, all python work should happen on the same thread as the rust caller.  Do I have that right?

**Comment by svevang** [comment]
There is a draft pep over here that could (maybe someday!) tackle this problem:
https://www.python.org/dev/peps/pep-0554/
Still a long way to get there.

Also, it's noted in that pep ^ that multiple sub-interpreters running in a single process all still interact with the GIL.
